#!/bin/bash

set -e

clog -t "erpnext: Build process starts ..."

# add schema
lcs-cli schema add --section erpnext

# bench supervisor config
cat > /etc/supervisor.conf.d/bench.conf <<EOF
[program:bench]
directory=${APP_DIR}
command=/home/erp/.local/bin/bench start
user=erp
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
EOF
clog -i "erpnext: Supervisor configuration for bench created."

# Create profile for global env in different shells
cat > /etc/profile.d/erpnext.sh <<EOF
export
export ERPNEXT_LOG_DIR=${ERPNEXT_LOG_DIR}
export ERPNEXT_DBHOST=${ERPNEXT_DBHOST}
EOF
clog -i "erpnext: Global ENVs added to /etc/profile.d"

# complete
clog -t "erpnext: Build process part 1/2 completed."
